config/routes.rb
Rails.application.routes.draw do
  # resources :admins

  get '/admin/login',     to: 'admins#new'
  post '/admin/login',    to: 'admins#create'
  get '/admin/applies',   to: 'admins#index'
  delete '/logout',       to: 'admins#destroy'


  root to: 'jobs#home'
  resources :entries,     only: [:new, :create, :show, :edit, :update]
  resources :cities,      only: :index
  resources :industries,  only: :index

  get '/apply', to: 'entries#new'
  resources :jobs do
    collection do
      get 'home'
      get 'city/:search',     to: 'jobs#index'
      get 'industry/:search', to: 'jobs#index'
      get 'search'
    end
  end
  devise_for :users
end

app/views/admins/_form.html.erb
<%= form_with(model: admin, local: true) do |form| %>
  <% if admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :admin_id %>
    <%= form.text_field :admin_id %>
  </div>

  <div class="field">
    <%= form.label :password_digest %>
    <%= form.text_field :password_digest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<%= link_to "Log out", logout_path, method: :delete %>

<h3>Applied jobs</h3>

<div class='container'>
  <%= form_tag(admin_applies_path, method: 'get') do %>

    <div class='form-group row'>
      <%= label_tag :email,'Email', class:'col-sm-2 col-form-label' %>
      <%= text_field_tag :email, nil, class: 'form-control col-md-6'%>
    </div>

    <div class='form-group row'>
      <%= label_tag 'city','City', class:'col-sm-2 col-form-label' %>
      <%= select_tag(:city_id, options_from_collection_for_select(@cities,:id, :name,9), class: 'form-control col-md-6') %>
    </div>

    <div class='form-group row'>
      <%= label_tag 'industry','Industry', class:'col-sm-2 col-form-label' %>
      <%= select_tag(:industry_id, options_from_collection_for_select(@industries,:id, :name,6), class: 'form-control col-md-6') %>
    </div>

    <div class='form-group row'>
      <div class="col-sm-2">
        <%= label_tag 'date','Date', class:'col-form-label' %>
      </div>
      <div class="col-md-4">
        <%= select_date(date = 1.year.ago,option= { prefix: :start_date, with_css_classes: false}) %>
      </div>
      <div class="col-md-4">  
        <%= select_date(date = Time.now,option= { prefix: :end_date, with_css_classes: false}) %>
      </div>
    </div>
    
    <%= submit_tag 'Search', name: nil,
                      class: 'btn btn-outline-success my-2 my-sm-0' %>
  <% end %>
</div><br>

<div class='container'>
  <h3>Search result:</h3>

  <%= paginate @entries %>
  <%= render @entries %>
  <%= paginate @entries %>
</div>

app/views/admins/new.html.erb
<h3>Admin login</h3>

<%#= render 'form', admin: @admin %>
<%= form_for(@admin, url: admin_login_path) do |form| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> when login:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :admin_id %><br>
    <%= form.text_field :admin_id %>
  </div>

  <div class="field">
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>

  <div class="actions">
    <%= form.submit "Log in" %>
  </div>
<% end %>