config/routes.rb
Rails.application.routes.draw do
  # resources :admins

  get '/admin/login',     to: 'admins#new'
  post '/admin/login',    to: 'admins#create'
  get '/admin/applies',   to: 'admins#index'
  delete '/logout',       to: 'admins#destroy'


  root to: 'jobs#home'
  resources :entries,     only: [:new, :create, :show, :edit, :update]
  resources :cities,      only: :index
  resources :industries,  only: :index

  get '/apply', to: 'entries#new'
  resources :jobs do
    collection do
      get 'home'
      get 'city/:search',     to: 'jobs#index'
      get 'industry/:search', to: 'jobs#index'
      get 'search'
    end
  end
  devise_for :users
end

app/models/entry.rb
class Entry < ApplicationRecord
  belongs_to :user, foreign_key: 'user_id'
  belongs_to :job, foreign_key: 'job_id'
  validates :entry_name, presence: true
  validates :entry_email, presence: true

  def self.search(hs = { email: '*', city_id: 1, industry_id: 1, start_date: 1.year.ago, end_date: Time.current})
    search_city = if hs[:city_id].to_i == City.find_by(slug: 'tat-ca-dia-diem').id
                    ""
                  else
                    hs[:city_id].to_s
                  end
    search_industry = if hs[:industry_id].to_i == Industry.find_by(slug: 'tat-ca-nganh-nghe').id
                        ""
                      else
                        hs[:industry_id].to_s
                      end

    entries = Entry.where("city like ? AND industry like ? AND updated_at BETWEEN ? AND ?",
                                "%#{search_city}%",
                                "%#{search_industry}%",
                                hs[:start_date],
                                hs[:end_date] )
  end
end

app/controllers/entries_controller.rb
# frozen_string_literal: true

class EntriesController < ApplicationController
  before_action :set_entry, only: [:show, :edit, :update]
  before_action :entry_params, only: [:create]

  # GET /entries/1
  # GET /entries/1.json
  def show; end

  # GET /entries/new
  def new
    @entry = if user_signed_in?
               Entry.new(entry_name:    current_user.name,
                         entry_email:   current_user.email,
                         entry_phone:   current_user.phone,
                         entry_address: current_user.address)
             else
               Entry.new
             end
  end

  # POST /entries
  # POST /entries.json
  def create
    @entry = Entry.new(entry_params)
    # render(:new) && return unless @entry.valid?

    @job = Job.find(params[:job_id])

    @user = User.find_by(email: params[:entry][:entry_email])
    unless @user
      random_password = Devise.friendly_token
      @user = User.new(name:   params[:entry][:entry_name],
                       email:   params[:entry][:entry_email],
                       phone:   params[:entry][:entry_phone],
                       address: params[:entry][:entry_address],
                       password:              random_password,
                       password_confirmation: random_password)
      render(:new) && return unless @user.valid?
      @user.skip_confirmation!
      @user.save
    end

    @entry.user_id = @user.id
    @entry.job_id = @job.id

    if @user.jobs.find_by(id: @job.id)
      redirect_to job_url(@job), flash: { secondary: 'You has been entry this job.' }
    else
      if @entry.save
        UserMailer.job_apply(@user, @job).deliver_now
        redirect_to @entry, flash: { secondary: 'Thank you for apply. Please check your email.' }
      else
        render :new
      end
    end
  end

  # PATCH/PUT /entries/1
  # PATCH/PUT /entries/1.json
  def update
    if @entry.update(entry_params)
      redirect_to @entry, notice: 'Entry was successfully updated.'
    else
      render :edit
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entry
    @entry = Entry.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def entry_params
    params.require(:entry).permit(:entry_name, :entry_email, :entry_phone, :entry_address)
  end
end

app/helpers/entries_helper.rb
module EntriesHelper
end

app/views/entries/_entry.html.erb
<div class='card' style='width: 40rem;'>
  <span class='card-body'>
    <h4 class='card-title'><%= link_to entry.job.title, entry.job %></h4>
    <p class='card-text'>Name: <%= entry.entry_name %></p>
    <p class='card-text'>Location: <%= entry.job.cities.map(&:name).reject(&:blank?).join(', ')%></p>
    <span class='card-text col-md-4'>Email: <%= entry.entry_email %></span>
    <span class='card-text col-md-4'>Applied date: <%= entry.created_at.strftime("%Y-%m-%d") %></span>
</div>
<br>

app/views/entries/_form.html.erb
<%= form_with(model: entry, local: true) do |form| %>
  <% if entry.errors.any? %>
    <div id="error_explanation">
      <h5><%= pluralize(entry.errors.count, "error") %> prohibited this entry from being saved:</h5>

      <ul>
      <% entry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= hidden_field_tag :job_id, @job.id %>

  <%= form.label :name %><br>
  <%= form.text_field :entry_name, class: 'form-control col-sm-6' %><br>

  <%= form.label :email %><br>
  <%= form.email_field :entry_email, class: 'form-control col-sm-6' %><br>

  <%= form.label :phone %><br>
  <%= form.telephone_field :entry_phone, class: 'form-control col-sm-6' %><br>

  <%= form.label :address %><br>
  <%= form.text_area :entry_address, class: 'form-control col-sm-6' %><br>

  <%= form.submit yield(:button_text), class: "btn btn-secondary" %>
  <%= link_to 'Back', :back, class: "btn btn-secondary"  %>
<% end %>

app/views/entries/confirm.html.erb
<% @job = Job.find(params[:job_id]) %>
<% @user = User.find(params[:user_id]) %>
<h3> Apply Job: <%= @job.title %></h3>
<h3> New > Confirm > Finish </h3>

<p>Job title: <%= @job.title %></p>
<p>User name: <%= @user.name %></p>
<p>User email: <%= @user.email %></p>

<%= link_to "Edit", apply_path( job_id: @job.id,
                                entries: { name: @user.name,
                                           email: @user.email }),
                    class: "btn btn-success" %>

<%= link_to "Apply", done_path( job_id: @job.id,
                                name: @user.name,
                                email: @user.email),
                    class: "btn btn-success" %>

app/views/entries/edit.html.erb
<% provide(:button_text, 'Save') %>
<% @job = Job.find(@entry.job_id) %>
<h1>Editing Entry</h1>

<%= render 'form', entry: @entry %>

app/views/entries/new.html.erb
<% provide(:button_text, 'Apply') %>
<% @job = Job.find(params[:job_id]) %>
<h3>Job_title: <%= @job.title %> </h3>
<% provide(:job_id, @job.id) %>

<%= render 'form', entry: @entry %>

app/views/entries/show.html.erb
<% @job = Job.find(@entry.job_id) %>
<h3>Id: <%= @job.id %> -- Job_title: <%= @job.title %> </h3>

<p>
  <strong>Name:</strong>
  <%= @entry.entry_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @entry.entry_email %>
</p>

<%= link_to 'Edit', edit_entry_path(id: @entry.id), class: "btn btn-secondary" %>
<%= link_to 'Back', job_path(@job), class: "btn btn-secondary"  %>