config/routes.rb
Rails.application.routes.draw do
  # resources :admins

  get '/admin/login',     to: 'admins#new'
  post '/admin/login',    to: 'admins#create'
  get '/admin/applies',   to: 'admins#index'
  delete '/logout',       to: 'admins#destroy'


  root to: 'jobs#home'
  resources :entries,     only: [:new, :create, :show, :edit, :update]
  resources :cities,      only: :index
  resources :industries,  only: :index

  get '/apply', to: 'entries#new'
  resources :jobs do
    collection do
      get 'home'
      get 'city/:search',     to: 'jobs#index'
      get 'industry/:search', to: 'jobs#index'
      get 'search'
    end
  end
  devise_for :users
end

app/models/job.rb
# frozen_string_literal: true

class Job < ApplicationRecord
  belongs_to :company, foreign_key: 'company_id'

  has_many :cities_jobs,  foreign_key: 'job_id',
                          dependent: :destroy
  has_many :cities, through: :cities_jobs

  has_many :industries_jobs,  foreign_key: 'job_id',
                              dependent: :destroy
  has_many :industries, through: :industries_jobs

  has_many :entries, foreign_key: 'job_id'
  has_many :users, through: :entries

  validates :title, presence: true, length: { maximum: 255 },
                    uniqueness: { case_sensitive: false }

  validates :position, presence: true, length: { maximum: 255 }
  # VALID_NUMBER_REGEX = /\A((\d{0,12}(\.\d{0,2})?)|(\.\d{0,2}))\z/
  # validates :salary, presence: true,
  #                    format: { with: VALID_NUMBER_REGEX },
  #                    numericality: {
  #                      greater_than: 0.00,
  #                      less_than: 999_999_999_999.99
  #                    }
  validates :salary, presence: true

  validates :expiry_date, presence: true
  validates :description, presence: true, length: { maximum: 1000 }
  validates :update_date, presence: true
  validates :published, presence: true, inclusion: { in: [true, false] }
  validates :welfare, presence: true, length: { maximum: 1000 }
  validates :condition, presence: true, length: { maximum: 1000 }
  validates :link, presence: true


  def self.search(search_hash = { kw: '*', page: 0})
    jobs = { job_id: [], job_num: 0 }
    solr = RSolr.connect url: Settings.solr.url
    search_params = { q: "search_text:#{search_hash[:kw]}",
                      start: search_hash[:page] * Kaminari.config.default_per_page,
                      rows: Kaminari.config.default_per_page }
    response_solr = solr.get 'select', params: search_params
    if response_solr['response']['numFound'] > 0
      jobs[:num] = response_solr['response']['numFound']
      response_solr['response']['docs'].collect do |row|
        jobs[:job_id] << row['job_id']
      end
    end
    jobs
  end
end

app/controllers/jobs_controller.rb
# frozen_string_literal: true

class JobsController < ApplicationController
  def index
    search_str = search_filter
    job_found = Job.search(kw: search_str, page: params[:page].to_i)
    job_ids = job_found[:job_id]
    @job_num = job_found[:num]
    job_search_result = Job.where(id: job_ids)
    @jobs = Kaminari.paginate_array(job_search_result, total_count: @job_num)
                    .page(params[:page])
  end

  def show
    @job = Job.find(params[:id])
  end

  def city
    @cities = City.all.select { |city| city.jobs.any? }
  end

  def home
    @jobs = Job.all.order(updated_at: :desc).take(5)
    @cities = City.all.select { |city| city.jobs.any? }.take(9)
    @industries = Industry.all.select { |industry| industry.jobs.any? }.take(9)
  end

  private

  def search_filter
    params.permit(:search)
    s = params[:search].blank? ? '*' : params[:search]
    s.gsub(/[\/]/,'*')
  end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_job.html.erb
<div class='card' style='width: 40rem;'>
  <span class='card-body'>
    <h4 class='card-title'><%=link_to job.title, job %></h4>
    <p class='card-text' ><strong>Description:</strong> <%= job.description.split('.').first %></p>
    <span class='card-text col-md-4'><strong>Location:</strong> <%= job.cities.map(&:name).reject(&:blank?).join(', ') %> </span>
    <span class='card-text col-md-4'><strong>Salary:</strong> <%= job.salary %></span><br>
    <span class='card-link col-md-4'><%= link_to 'Show', job %></span>
</div>
<br>

app/views/jobs/home.html.erb
<div class='container'>
  <h3>Total: <%= pluralize(Job.count , 'job') %></h3><br>
  <div class='container'>
    <%= form_tag( jobs_path,
                  method: 'get',
                  class: 'form-inline') do %>
    <%= text_field_tag :search, params[:search],
                        placeholder: 'search job',
                        class: 'form-control mr-sm-2'%>
    <%= submit_tag 'Search', name: nil,
                    class: 'btn btn-outline-success my-2 my-sm-0' %>
    <% end %>
  </div> <br>

  <div class='container'>
    <ul class='list-group'>
      <% @jobs.each do |job| %>
        <li class='list-group-item link'>
          <%= link_to job.title, job %>
        </li>
      <% end %>  
    </ul>
  </div><br>

  <div class='container'>
  <h4>City:</h4>

  <div class="container">
    <div class="row">
      <% @cities.each do |city| %>
        <div class="col-6 col-md-4 list-group-item">
          <%= city.name %>
          <%= link_to pluralize(city.jobs.count, 'job'),
                      controller: 'jobs',
                      action: 'index',
                      search: city.name %>
        </div>
      <% end %>
    </div>
  </div><br>

  <h4>Industry:</h4>
  <div class="container">
    <div class="row">
      <% @industries.each do |industry| %>
        <div class="col-6 col-md-4 list-group-item">
          <%= industry.name %>
          <%= link_to pluralize(industry.jobs.count, 'job'),
                      controller: 'jobs',
                      action: 'index',
                      search: industry.name %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/jobs/index.html.erb
<div class='container'>
  <div class='container'>
    <%= form_tag(jobs_path, method: 'get',
                        class: 'form-inline') do %>
        <%= text_field_tag :search, params[:search],
                        placeholder: 'Search Jobs',
                        class: 'form-control mr-sm-2'%>
        <%= submit_tag 'Search', name: nil,
                        class: 'btn btn-outline-success my-2 my-sm-0' %>
    <% end %>
  </div><br>

  <div class='container'>
    <h3>Search result: <%= pluralize(@job_num , 'job') %></h3><br>

    <%= paginate @jobs%>
    <%= render @jobs %>
    <%= paginate @jobs%>
  </div>
</div>

app/views/jobs/jobs_in_city.html.erb
<h4><%= @city.name %>: <%= pluralize(@city.jobs.count, 'job') %></h4>
<div class='container'>
  <div class='jobs-list'>
    <ul>
      <%= paginate @jobs, outer_window: 3 %>
      <%= render @jobs %>
    </ul>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="row">
  <aside class="col-md-16">
    <section class="user_info">

      <h4>
        <%= @job.title %> 
      </h4>
      <p> 
        <%= link_to "Apply",  apply_path(job_id: @job.id),
                            class: "btn btn-secondary" %>
      </p><br>

      <table class="table table-hover">
        <tbody>
          <tr>
            <th scope="row">Job title</th>
            <td><%= @job.title %></td>
          </tr>
          <tr>
            <th scope="row">Company</th>
            <td><%= @job.company.name %></td>
          </tr>
          <tr>
            <th scope="row">Location</th>
            <td>
              <%= @job.cities.map(&:name).reject(&:blank?).join(', ') %>
            </td>
          </tr>
          <tr>
            <th scope="row">Salary</th>
            <td><%= @job.salary %></td>
          </tr>
          <tr>
            <th scope="row">Description</th>
            <td><%= @job.description %></td>
          </tr>
        </tbody>
      </table>

      <%= link_to "Apply",  apply_path(job_id: @job.id),
                            class: "btn btn-secondary" %>
      <%= link_to 'Back', :back, class: "btn btn-secondary" %>
    </section> 
  </aside>
</div>